"""Add indexes for search

Revision ID: bfd6af3d2235
Revises: 35b4dee5cf93
Create Date: 2026-02-27 13:21:05.866105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd6af3d2235'
down_revision: Union[str, Sequence[str], None] = '35b4dee5cf93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_devices_ip_address'), 'devices', ['ip_address'], unique=False)
    op.create_index(op.f('ix_devices_owner'), 'devices', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_owner'), table_name='devices')
    op.drop_index(op.f('ix_devices_ip_address'), table_name='devices')
    # ### end Alembic commands ###
