"""add_half_rack_fields_and_audit_log

Revision ID: e10218648318
Revises: bfd6af3d2235
Create Date: 2026-03-02 20:12:04.183712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10218648318'
down_revision: Union[str, Sequence[str], None] = 'bfd6af3d2235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.add_column('devices', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('oob_ip', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('os', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('asset_tag', sa.String(), nullable=True))
    op.create_index(op.f('ix_devices_asset_tag'), 'devices', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_devices_oob_ip'), 'devices', ['oob_ip'], unique=False)
    op.create_index(op.f('ix_devices_os'), 'devices', ['os'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_os'), table_name='devices')
    op.drop_index(op.f('ix_devices_oob_ip'), table_name='devices')
    op.drop_index(op.f('ix_devices_asset_tag'), table_name='devices')
    op.drop_column('devices', 'asset_tag')
    op.drop_column('devices', 'os')
    op.drop_column('devices', 'oob_ip')
    op.drop_column('devices', 'notes')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
